In [12]:
import pandas as pd
import numpy as np

In [13]:
data=pd.read_csv('/content/Kanpur_House_Data.csv')

In [14]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Plot Area,Under Construction,"Govind Nagar, Kanpur",2 BHK,Kanpur Residency 1,3336,3,1,156.72
1,Built-up Area,Immediate Possession,"Civil Lines, Kanpur",2 BHK,Kanpur Residency 2,1485,4,0,166.58
2,Plot Area,Ready To Move,"Civil Lines, Kanpur",4 BHK,Kanpur Residency 3,1249,5,3,157.07
3,Super built-up Area,Ready To Move,"Ashok Nagar, Kanpur",4 BHK,Kanpur Residency 4,2152,3,0,71.97
4,Super built-up Area,Under Construction,"Ashok Nagar, Kanpur",1 BHK,Kanpur Residency 5,3014,2,2,107.44

In [15]:
data.shape

(200, 9)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     200 non-null    object
 1   availability  200 non-null    object
 2   location      200 non-null    object
 3   size          200 non-null    object
 4   society       200 non-null    object
 5   total_sqft    200 non-null    int64
 6   bath          200 non-null    int64
 7   balcony       200 non-null    int64
 8   price         200 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 14.2+ KB

In [17]:
for column in data.columns:
  print(data[column].value_counts())
  print("*"*20)

area_type
Built-up Area          69
Super built-up Area    66
Plot Area              65
Name: count, dtype: int64
********************
availability
Ready To Move           70
Under Construction      67
Immediate Possession    63
Name: count, dtype: int64
********************
location
Civil Lines, Kanpur      27
Panki, Kanpur            27
Kidwai Nagar, Kanpur     25
Kakadeo, Kanpur          21
Arya Nagar, Kanpur       19
Ashok Nagar, Kanpur      19
Swaroop Nagar, Kanpur    18
Govind Nagar, Kanpur     15
Kalyanpur, Kanpur        15
Shyam Nagar, Kanpur      14
Name: count, dtype: int64
********************
size
1 BHK    46
4 BHK    44
2 BHK    43
5 BHK    37
3 BHK    30
Name: count, dtype: int64
********************
society
Kanpur Residency 1      1
Kanpur Residency 2      1
Kanpur Residency 3      1
Kanpur Residency 4      1
Kanpur Residency 5      1
                       ..
Kanpur Residency 196    1
Kanpur Residency 197    1
Kanpur Residency 198    1
Kanpur Residency 199    1
Kanpur Residency 200    1
Name: count, Length: 200, dtype: int64
********************
total_sqft
915     2
1386    2
1543    2
1117    2
2152    1
       ..
1281    1
1605    1
2450    1
2749    1
1449    1
Name: count, Length: 196, dtype: int64
********************
bath
1    45
3    44
4    42
5    35
2    34
Name: count, dtype: int64
********************
balcony
0    61
2    52
1    48
3    39
Name: count, dtype: int64
********************
price
233.92    2
166.58    1
156.72    1
71.97     1
107.44    1
         ..
104.51    1
43.97     1
183.29    1
155.88    1
205.21    1
Name: count, Length: 199, dtype: int64
********************

In [18]:
data.isna().sum()

area_type       0
availability    0
location        0
size            0
society         0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [19]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [20]:
data.describe()

        total_sqft        bath       price
count   200.000000  200.000000  200.000000
mean   1997.425000    2.940000  129.510500
std     825.588339    1.409373   68.883124
min     617.000000    1.000000   15.260000
25%    1291.750000    2.000000   68.977500
50%    2024.500000    3.000000  126.510000
75%    2642.500000    4.000000  184.575000
max    3496.000000    5.000000  249.450000

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    200 non-null    object
 1   size        200 non-null    object
 2   total_sqft  200 non-null    int64
 3   bath        200 non-null    int64
 4   price       200 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 7.9+ KB

In [22]:
data['location'].value_counts()

location
Civil Lines, Kanpur      27
Panki, Kanpur            27
Kidwai Nagar, Kanpur     25
Kakadeo, Kanpur          21
Arya Nagar, Kanpur       19
Ashok Nagar, Kanpur      19
Swaroop Nagar, Kanpur    18
Govind Nagar, Kanpur     15
Kalyanpur, Kanpur        15
Shyam Nagar, Kanpur      14
Name: count, dtype: int64

In [23]:
data['location']=data['location'].fillna('Swaroop Nagar')

In [24]:
data['size'].value_counts()

size
1 BHK    46
4 BHK    44
2 BHK    43
5 BHK    37
3 BHK    30
Name: count, dtype: int64

In [25]:
data['size']=data['size'].fillna('3BHK')

In [26]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    200 non-null    object
 1   size        200 non-null    object
 2   total_sqft  200 non-null    int64
 3   bath        200 non-null    int64
 4   price       200 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 7.9+ KB

In [28]:
data['bhk']=data['size'].str.extract('(\d+)').astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_5759/226855085.py:1: SyntaxWarning: invalid escape sequence '\d'
  data['bhk']=data['size'].str.extract('(\d+)').astype(int)

In [29]:
data[data.bhk > 3]

                  location   size  total_sqft  bath   price  bhk
2      Civil Lines, Kanpur  4 BHK        1249     5  157.07    4
3      Ashok Nagar, Kanpur  4 BHK        2152     3   71.97    4
8    Swaroop Nagar, Kanpur  5 BHK        2486     5   77.63    5
9      Civil Lines, Kanpur  5 BHK        1316     1  248.85    5
12     Civil Lines, Kanpur  4 BHK        3406     1  181.99    4
..                     ...    ...         ...   ...     ...  ...
187      Kalyanpur, Kanpur  4 BHK        2185     2  168.53    4
191    Ashok Nagar, Kanpur  4 BHK         840     5   85.31    4
193      Kalyanpur, Kanpur  4 BHK        3264     5   90.48    4
197          Panki, Kanpur  4 BHK        2450     4  183.29    4
199   Kidwai Nagar, Kanpur  4 BHK        1449     1  205.21    4

[81 rows x 6 columns]

In [30]:
data['total_sqft'].unique()

array([3336, 1485, 1249, 2152, 3014, 1690, 3255, 2411, 2486, 1316,  641,
       1543, 3406,  699, 1756,  915, 1386, 1323, 2570, 2139, 3460,  891,
       1784, 2585,  799, 1884, 3332, 2871,  619, 1076, 1786,  884, 1100,
       1559, 3139, 2569, 1123, 1068, 3295, 3132, 1291, 3360,  806, 2046,
       1685, 1707, 1551, 1962, 2538, 2319, 2784, 3466, 1144, 1292, 2038,
       1035, 2206, 3320, 1541, 3318, 2605, 2821, 1965, 3175, 2663, 2834,
        839, 1665, 1883, 2963, 2522, 1242,  785, 1226,  887, 2080, 1585,
       1523, 1073, 1920, 2805, 3496, 2239, 2882, 2325, 2096, 2594, 2420,
       2773, 2470, 1546,  717, 1392,  736, 2285, 2227, 3126, 1762, 1188,
       3444, 2756, 1681, 1661, 1115, 3231, 2508, 2597, 1892, 1916,  617,
       2483, 3283, 1345, 2662, 3097, 1686, 2042, 2250, 2267,  803, 1038,
       3372, 3005, 1166, 1516, 3468, 1457, 2932, 2736, 3194, 2444,  813,
       2090, 1117, 2164, 1463, 2948, 1646, 2417, 2497,  657, 2024,  620,
       1273, 1657, 2957, 1139, 3233,  790,  732, 3094, 2134,  831, 1767,
       1610, 2427, 2182, 1023,  668, 2922, 1861,  870, 2248, 3138, 2443,
       1783, 2703, 2407, 1489, 2025, 1815, 2044,  671,  638, 2615, 2259,
       2667, 2138, 1911, 2177, 1085,  802, 2409, 2185, 2636, 2797, 3488,
        840, 2665, 3264, 1886, 1281, 1605, 2450, 2749, 1449])

In [31]:
def covertRange(x):
  temp=x.split('-')
  if len(temp) == 2:
    return (float(temp[0]) + float(temp[1]))/2
  try:
    return float(x)
  except:
    return None

In [32]:
data.head()

               location   size  total_sqft  bath   price  bhk
0  Govind Nagar, Kanpur  2 BHK        3336     3  156.72    2
1   Civil Lines, Kanpur  2 BHK        1485     4  166.58    2
2   Civil Lines, Kanpur  4 BHK        1249     5  157.07    4
3   Ashok Nagar, Kanpur  4 BHK        2152     3   71.97    4
4   Ashok Nagar, Kanpur  1 BHK        3014     2  107.44    1

In [33]:
data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [34]:
data['price_per_sqft']

0       4697.841727
1      11217.508418
2      12575.660528
3       3344.330855
4       3564.698076
           ...
195     8158.469945
196     2739.563863
197     7481.224490
198     5670.425609
199    14162.180814
Name: price_per_sqft, Length: 200, dtype: float64

In [35]:
data.describe()

        total_sqft        bath       price         bhk  price_per_sqft
count   200.000000  200.000000  200.000000  200.000000      200.000000
mean   1997.425000    2.940000  129.510500    2.915000     7989.917261
std     825.588339    1.409373   68.883124    1.448539     6402.439719
min     617.000000    1.000000   15.260000    1.000000      499.406880
25%    1291.750000    2.000000   68.977500    2.000000     3672.629337
50%    2024.500000    3.000000  126.510000    3.000000     6512.914342
75%    2642.500000    4.000000  184.575000    4.000000     9725.113726
max    3496.000000    5.000000  249.450000    5.000000    36427.457098

In [36]:
data['location'].value_counts()

location
Civil Lines, Kanpur      27
Panki, Kanpur            27
Kidwai Nagar, Kanpur     25
Kakadeo, Kanpur          21
Arya Nagar, Kanpur       19
Ashok Nagar, Kanpur      19
Swaroop Nagar, Kanpur    18
Govind Nagar, Kanpur     15
Kalyanpur, Kanpur        15
Shyam Nagar, Kanpur      14
Name: count, dtype: int64

In [37]:
data['location']=data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

In [38]:
location_count_less_2 = location_count[location_count <= 2]
location_count_less_2

Series([], Name: count, dtype: int64)

In [39]:
data['location']=data['location'].apply(lambda x:'other' if x in location_count_less_2 else x)

In [40]:
data['location'].value_counts()

location
Civil Lines, Kanpur      27
Panki, Kanpur            27
Kidwai Nagar, Kanpur     25
Kakadeo, Kanpur          21
Arya Nagar, Kanpur       19
Ashok Nagar, Kanpur      19
Swaroop Nagar, Kanpur    18
Govind Nagar, Kanpur     15
Kalyanpur, Kanpur        15
Shyam Nagar, Kanpur      14
Name: count, dtype: int64

In [41]:
data.describe()

        total_sqft        bath       price         bhk  price_per_sqft
count   200.000000  200.000000  200.000000  200.000000      200.000000
mean   1997.425000    2.940000  129.510500    2.915000     7989.917261
std     825.588339    1.409373   68.883124    1.448539     6402.439719
min     617.000000    1.000000   15.260000    1.000000      499.406880
25%    1291.750000    2.000000   68.977500    2.000000     3672.629337
50%    2024.500000    3.000000  126.510000    3.000000     6512.914342
75%    2642.500000    4.000000  184.575000    4.000000     9725.113726
max    3496.000000    5.000000  249.450000    5.000000    36427.457098

In [42]:
(data['total_sqft']/data['bhk']).describe()

count     200.000000
mean      959.455917
std       744.256777
min       127.600000
25%       423.625000
50%       777.000000
75%      1230.000000
max      3488.000000
dtype: float64

In [43]:
data=data[((data['total_sqft']/data['bhk']) >= 300)]
data.describe()

        total_sqft        bath       price         bhk  price_per_sqft
count   169.000000  169.000000  169.000000  169.000000      169.000000
mean   2189.426036    2.928994  131.311716    2.644970     6944.005353
std     746.787267    1.420823   68.711884    1.390226     5233.615438
min     619.000000    1.000000   16.840000    1.000000      499.406880
25%    1646.000000    2.000000   69.870000    1.000000     3208.252740
50%    2185.000000    3.000000  135.250000    2.000000     5776.504298
75%    2756.000000    4.000000  184.220000    4.000000     8736.902050
max    3496.000000    5.000000  249.450000    5.000000    36427.457098

In [44]:
data.shape

(169, 7)

In [45]:
data.price_per_sqft.describe()

count      169.000000
mean      6944.005353
std       5233.615438
min        499.406880
25%       3208.252740
50%       5776.504298
75%       8736.902050
max      36427.457098
Name: price_per_sqft, dtype: float64

In [46]:
def remove_outliers_sqft(df):
  df_output=pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m = np.mean(subdf.price_per_sqft)
    st = np.std(subdf.price_per_sqft)
    gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
    df_output = pd.concat([df_output,gen_df],ignore_index = True)
  return df_output
data = remove_outliers_sqft(data)
data.describe()

        total_sqft        bath       price         bhk  price_per_sqft
count   123.000000  123.000000  123.000000  123.000000      123.000000
mean   2323.186992    2.861789  135.001870    2.699187     5988.766734
std     671.777583    1.444749   58.604857    1.419622     2476.907103
min     806.000000    1.000000   24.670000    1.000000      763.068358
25%    1785.000000    1.000000   85.360000    1.000000     4002.426967
50%    2325.000000    3.000000  141.120000    2.000000     5670.425609
75%    2809.000000    4.000000  177.075000    4.000000     7721.994976
max    3496.000000    5.000000  246.280000    5.000000    12445.568114

In [47]:
def bhk_outlier_remover(df):
  exclude_indices = np.array([])
  for location, location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk, bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] ={
          'mean': np.mean(bhk_df.price_per_sqft),
          'std': np.std(bhk_df.price_per_sqft),
          'count': bhk_df.shape[0]
      }

      for bhk, bhk_df in location_df.groupby('bhk'):
        stats = bhk_stats.get(bhk-1)
        if stats and stats['count']>5:
          exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
  return df.drop(exclude_indices,axis='index')

In [48]:
data=bhk_outlier_remover(data)

In [49]:
data.shape

(116, 7)

In [50]:
data

,location,size,total_sqft,bath,price,bhk,price_per_sqft
0,"Arya Nagar, Kanpur",1 BHK,1756,5,153.42,1,8736.902050
1,"Arya Nagar, Kanpur",2 BHK,3460,3,246.01,2,7110.115607
2,"Arya Nagar, Kanpur",2 BHK,1786,4,122.38,2,6852.183651
3,"Arya Nagar, Kanpur",1 BHK,2046,4,108.86,1,5320.625611
4,"Arya Nagar, Kanpur",4 BHK,2038,3,43.43,4,2131.010795
...,...,...,...,...,...,...,...
118,"Swaroop Nagar, Kanpur",2 BHK,2756,4,222.36,2,8068.214804
119,"Swaroop Nagar, Kanpur",2 BHK,2444,1,172.52,2,7058.919804
120,"Swaroop Nagar, Kanpur",5 BHK,2164,3,167.86,5,7756.931608
121,"Swaroop Nagar, Kanpur",2 BHK,1657,4,173.76,2,10486.421243
122,"Swaroop Nagar, Kanpur",3 BHK,2667,3,238.54,3,8944.131984

In [51]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

In [52]:
data.head()

             location  total_sqft  bath   price  bhk
0  Arya Nagar, Kanpur        1756     5  153.42    1
1  Arya Nagar, Kanpur        3460     3  246.01    2
2  Arya Nagar, Kanpur        1786     4  122.38    2
3  Arya Nagar, Kanpur        2046     4  108.86    1
4  Arya Nagar, Kanpur        2038     3   43.43    4

In [53]:
data.to_csv('cleaned_data.csv')

In [54]:
x=data.drop(columns=['price'])
y=data['price']

In [55]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [57]:
print(x_train.shape)
print(x_test.shape)

(92, 4)
(24, 4)

In [58]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')

In [59]:
scaler = StandardScaler()

In [60]:
lr = LinearRegression()

In [61]:
pipe = make_pipeline(column_trans,scaler,lr)

In [62]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [63]:
y_pred_lr = pipe.predict(x_test)

In [64]:
r2_score(y_test,y_pred_lr)

0.19719533084455687

In [65]:
lasso = Lasso()

In [66]:
pipe = make_pipeline(column_trans,scaler,lasso)

In [67]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [68]:
y_pred_lasso = pipe.predict(x_test)
r2_score(y_test,y_pred_lasso)

0.2098956483028731

In [69]:
ridge = Ridge()

In [70]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [71]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [72]:
y_pred_ridge = pipe.predict(x_test)
r2_score(y_test,y_pred_ridge)

0.19855042409637147

In [73]:
print("No Regularization:", r2_score(y_test,y_pred_lr))
print("Lasso:", r2_score(y_test,y_pred_lasso))
print("Ridge:", r2_score(y_test,y_pred_ridge))

No Regularization: 0.19719533084455687
Lasso: 0.2098956483028731
Ridge: 0.19855042409637147

In [74]:
import pickle

In [75]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [76]:
import joblib
joblib.dump(pipe,"RidgeModel_new.joblib")
print("Saved successfully!")

Saved successfully!

In [77]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import Ridge
from sklearn.pipeline import make_pipeline
import joblib

column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),remainder='passthrough')
scaler = StandardScaler()
ridge = Ridge()
pipe = make_pipeline(column_trans,scaler,ridge)
pipe.fit(x_train,y_train)
joblib.dump(pipe,"RidgeModel_new.joblib")
print("RidgeModel_new.joblib saved successfully!")

RidgeModel_new.joblib saved successfully!

In [78]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 100.5 MB/s eta 0:00:00
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 96.5 MB/s eta 0:00:00
Installing collected packages: pydeck, streamlit
Successfully installed pydeck-0.9.2 streamlit-1.58.0

In [79]:

#%%writefile kanpur-house-price-predictor/app.py
import streamlit as st
import joblib
import pandas as pd

try:
  model = joblib.load('kanpur-house-price-predictor/model.pkl')
except FileNotFoundError:
  st.error("Model file 'kanpur-house-price-predictor/model.pkl' not found. Please ensure it has been saved correctly.")
  st.stop()

st.title("Kanpur House Price Prediction")
st.header('Enter House Details')

location = st.selectbox('Location',['other','Civil Lines','Panki','Kidwai Nagar','Kakadeo','Arya Nagar','Ashok Nagar','Swaroop Nagar','Govind Nagar','Kalyanpur','Shyam Nagar'])
total_sqft = st.number_input('Total Sqaure Feet',min_value=300.0, max_value=5000.0)
bath = st.slider('Number of Bathrooms',min_value=1, max_value=6)
bhk= st.slider('Number of BHK', min_value=1, max_value=10)

if st.button('Predict Price'):
  input_data = pd.DataFrame([{
      'location': location,
      'total_sqft': total_sqft,
      'bath': float(bath),
      'bhk': float(bhk)
  }])

  predicted_price = model.predict(input_data)[0]
  st.success(f'Predicted Price: ₹{predicted_price:.2f} Lakhs')

2026-06-22 16:18:03.478 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:03.987
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]
2026-06-22 16:18:03.988 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:03.995 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:03.999 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.003 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.020 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.026 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.028 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.034 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.038 Session state does not function when running a script without `streamlit run`
2026-06-22 16:18:04.045 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.053 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.104 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.115 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.117 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.123 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.125 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.127 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.131 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [80]:
import streamlit as st
import joblib
import pandas as pd
try:
  model = joblib.load("RidgeModel_new.joblib")
except FileNotFoundError:
  st.error("Model file 'RidgeModel_new.joblib' not found. Please ensure it has been saved correctly.")
  st.stop()
st.title('Kanpur House Price Prediction')
st.header('Enter House Deatils')
location = st.selectbox('Location',['other','Civil Lines','Panki','Kidwai Nagar','Kakadeo','Arya Nagar','Ashok Nagar','Swaroop Nagar','Govind Nagar','Kalyanpur','Shyam Nagar'])
total_sqft=st.number_input('Total Square Feet', min_value=300.0, max_value=5000.0)
bath = st.slider('Number of Bathrooms',min_value=1, max_value=6)
bhk= st.slider('Number of BHK', min_value=1, max_value=10)

if st.button('Predict Price'):
  input_data= pd.DataFrame([{
      'location': location,
      'total_sqft': total_sqft,
      'bath': float(bath),
      'bhk': float(bhk)
  }])

  predicted_price = model.predict(input_data)[0]
  st.success(f'Predicted Price: ₹{predicted_price:.2f} Lakhs')

2026-06-22 16:18:04.160 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.162 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.167 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.177 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.178 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.180 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.186 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.188 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.192 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.193 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.194 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.197 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.202 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.203 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.206 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.210 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.211 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.214 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.218 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.219 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.221 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.223 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.224 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.225 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.226 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.227 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.228 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.229 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.230 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-06-22 16:18:04.232 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [81]:
!pip install streamlit pyngrok joblib scikit-learn pandas numpy

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.58.0)
Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.4.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.50)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)
Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.49.0)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.8.0)
Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.32)
Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)
Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.18)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.5.20)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2026.5.1)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

In [82]:
!streamlit run app.py &>/content/logs.txt &

In [84]:
import os
print(os.listdir())

['.config', 'RidgeModel.pkl', 'cleaned_data.csv', 'logs.txt', 'Kanpur_House_Data.csv', 'RidgeModel_new.joblib', 'sample_data']

In [85]:
from google.colab import files
files.download('RidgeModel.pkl')

In [86]:
import pickle
with open('house_price_model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [87]:
import os
print(os.path.exists('house_price_model.pkl'))  # should print True
print(os.path.getsize('house_price_model.pkl'))  # should show a size in bytes, not 0

True
3158

In [88]:
import os
print(os.path.exists('RidgeModel.pkl'))
print(os.path.getsize('RidgeModel.pkl'))

True
2983

In [89]:
from google.colab import files
files.download('RidgeModel.pkl')

In [90]:
import sklearn
print(sklearn.__version__)

1.6.1

In [92]:
!mkdir -p kanpur-house-price-predictor

In [93]:
!mv RidgeModel_new.joblib kanpur-house-price-predictor/model.pkl
print("RidgeModel_new.joblib moved and renamed to Kanpur-house-price-predictor/model.pkl")

RidgeModel_new.joblib moved and renamed to Kanpur-house-price-predictor/model.pkl

In [94]:
import joblib

joblib.dump(pipe, 'RidgeModel_new.joblib')

['RidgeModel_new.joblib']

In [95]:
!python -c "import sklearn; print(sklearn.__version__)"

1.6.1